### ISSUE TITLE
Percentuale popolazione "di testata" vs percentuale di dettaglio

### ISSUE THREAD

**Issue by clasprea** [lorossi/vaccino-covid19#2]
Ciao Lorenzo,
complimenti per lavoro, davvero carino e ben fatto.
Magari non ho capito bene io come funzionano i dati, ma noto una discrepanza tra la % di popolazione riportata in alto nei totali (al momento 1,47%) rispetto alle percentuali riportate nella tabella poco sotto relativa ai dati splittati per regione.
La motivazione potrebbe essere data dal fatto che da una parte non considera che serva una doppia dose, mentre nel dettaglio sì, però non è chiarissimo così. 
Grazie

**Comment by lorossi** [comment]
Grazie mille per i complimenti.
Le percentuali per i territori vengono riportate esattamente come segnalate dal Ministero, mentre la percentuale totale della popolazione Italiana viene calcolata facendo il rapporto tra popolazione vaccinata e popolazione totale. Sospetto fortemente che i dati percentuali comunicati dal Ministero siano completamente sbagliati (basta vedere il grafico, la percentuale addirittura diminuisce per certe Regioni) tanto che la Liguria oscilla tra lo 0.23% e lo 0.58%.
Nella prossima versione del sito che rilascerò (stavolta hostata su una VPS, quindi senza magheggi per fare funzionare GitHub Pages) i dati percentuali sono calcolati da me senza basarmi su ciò che viene comunicato nei vollettini ufficiali.
Io dò per scontato che i dati si riferiscano solo alla prima dose, altrimenti il numero di vaccinati dovrebbe essere ancora zero (in quanto la seconda dose viene appunto inoculata dopo tre settimane).
